### ISSUE TITLE
Check Status Returning Status Code 400

### ISSUE THREAD

**Issue by rlcurrall** [Sweylo/CSCI_470_STV_BACKEND#1]
When calling the '_**check_match_status**_' request, if the match is currently in the '**Waiting**' or '**Pregame**' phase it will return a 400 status code. This is an issue due to how I am handling errors on client side.

From What I can tell, the issue comes up in the **_gameplay_actions.php_** file around line **14**. You have the function _get_match_and_validate_match_status_ take an input that is used to compare to the match status and throws the 400 status code if the two do not match. I don't think the function needs the input or comparison anymore but not sure if you had plans for it.

For reference:
```
function get_match_and_validate_match_status($match_status) {
    
    global $me;
    
    if (!$me) {
        send_to_client(401, null, 'must be logged in');
    }
    $match = get_match_by_user($me['user_id']);
    if (!$match->data) {
        send_to_client(400, null, 'you are not in a match');
    }
    if ($match['match_status'] != $match_status) {
        send_to_client(400, ['match_status' => $match['match_status']]);
    }
    
    return $match;
    
}
```
Is the function that you created and you are calling it as follows:
`$match = get_match_and_validate_match_status(MATCH_PLAYING);`

**Comment by Sweylo** [comment]
I hadn't originally intended for check_match_status to be used outside of playing. This is a necessary check, however I have added a parameter to check that a match's status value is no more than the passed for check_match_status. So basically it does a > comparison rather than != if the second parameter is true. It now returns 200 with whatever default data in the body. This will be in the next commit.
